"""The Broker protocol is the vendor-swap seam: a fake must satisfy it."""
from broker import (
    Account, AssetInfo, Bar, Broker, Clock, Order, OrderRequest,
    Position, PortfolioHistory, Quote,
)


def test_order_request_defaults():
    req = OrderRequest(symbol="AAPL", side="buy", order_type="market", notional=1000.0)
    assert req.qty is None
    assert req.limit_price is None
    assert req.stop_loss is None
    assert req.take_profit is None


def test_fake_broker_satisfies_protocol():
    class Fake:
        def get_account(self) -> Account: ...
        def get_positions(self) -> list[Position]: ...
        def get_quote(self, symbol: str) -> Quote: ...
        def get_daily_bars(self, symbol: str, start: str, end: str) -> list[Bar]: ...
        def get_clock(self) -> Clock: ...
        def get_asset(self, symbol: str) -> AssetInfo: ...
        def place_order(self, req: OrderRequest) -> Order: ...
        def cancel_order(self, order_id: str) -> None: ...
        def list_open_orders(self) -> list[Order]: ...
        def get_order(self, order_id: str) -> Order: ...
        def get_portfolio_history(self, period: str) -> PortfolioHistory: ...

    b: Broker = Fake()  # would fail type-check; at runtime, isinstance via runtime_checkable
    assert isinstance(Fake(), Broker)
